site:
  title: AsciiDoc How-to documentation
  #url: /contribute
  start_page: index.adoc

content:
  edit_url: 'https://github.com/datastax/adoc-howto/blob/master/{path}'
  sources:
    - url: '~/work/adoc-howto'
      branches: HEAD

output: 
  dir: ~/work/adoc-howto/build/site

ui:
  bundle:
    url: https://github.com/stargate/antora-ui-stargate/releases/download/v.0.7/ui-bundle.zip
  supplemental_files: ~/work/adoc-howto/playbooks/supplemental-ui
  # override the default _ dir for assets, as Jekyll will delete them
  output_dir: assets

asciidoc:
  attributes:
    source-highlighter: highlightjs
    page-pagination: ''
    idprefix: ''
    idseparator: '-'
  extensions:
  - ~/work/adoc-howto/playbooks/lib/tabs-block.js
